import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import classes from "./layout.module.css";
import Navbar from "@/components/layout/navbar";
import Footer from "@/components/layout/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Neogarden Database!",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body>
        <div className="grid min-h-screen grid-rows-[auto_1fr_auto] bg-[url('/images/background/background_temp.png')] bg-cover bg-fixed bg-center">
          <Navbar />

          <div className="md:p-large mx-0 w-full max-w-full border-0 bg-amber-50/90 p-2 md:mx-auto md:my-2 md:max-w-3xl md:border-2 md:border-black">
            <main>{children}</main>
          </div>

          <Footer />
        </div>
      </body>
    </html>
  );
}
