import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import classes from "./layout.module.css";
import Navbar from "@/components/layout/navbar";
import Footer from "@/components/layout/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Neogarden Database!",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body>
        <div className="grid min-h-screen grid-rows-[auto_1fr_auto] bg-amber-100">
          <Navbar></Navbar>
          <div className={`py-large`}>
            <main>{children}</main>
          </div>
          <div className="bg-amber-400">
            <p>Yay I'm a footer! Send me shit on Neopets!</p>
          </div>
        </div>
      </body>
    </html>
  );
}
