export const randomItemNames: string[] = [
  "Flower Picking Xweetok Gnome",
  "Atrabud",
  "Bluebells",
  "Budseed",
  "Dwarf Tree",
  "Gardenias",
  "Glass Roses",
  "White Lulu",
  "Yolkalia",
  "Boadaisy",
  "Pebeanjay Flowers",
  "Sponderolas",
  "Dragonbud",
  "Snake Rose",
  "Colour Lillies",
  "Orb Plant",
  "Potting Bench",
  "Spiky Bush",
  "Tami Veggie Plant",
  "Feather Weeds",
  "Large Thorn Growth",
  "Swab Bush",
  "Ring Vine",
  "Spine Vine",
  "Zobamints",
  "Tactis",
  "Rowzez",
  "Furrn",
  "Glant",
  "Mordongos",
  "Plantmelon",
  "Bluesticks",
  "Chick-a-Daisy",
  "Dunkydoos",
  "Rock Tree",
  "Pineapple Plant",
  "Pink Cyclamen",
  "Lilacs",
  "Lily of the Valley",
  "Spring Beauty",
  "Plant Cure",
  "Wooden Patio Table",
  "Red Poppies",
  "Citronella Candle",
  "Instant Roses",
  "Wooden Patio Chair",
  "Straw Patio Chair",
  "Checkered Umbrella",
  "Veggie Paving Stones",
  "Floating Ball Fountain",
  "Gooey Rotten Pumpkin",
  "Grass",
  "Refreshing Kyrii Fountain",
  "Sparkling Flotsam Fountain",
  "Straw Patio Table",
  "Cascading Gold Fountain",
  "Tether Ball",
  "Pink Tile Patio Table",
  "Curious Moehog Gnome",
  "Straw Umbrella",
  "Lawnmower",
  "Pink Pteri Gnome",
];
